language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
script:
  - jdk_switcher use openjdk6
  - mvn test
  - jdk_switcher use oraclejdk7
  - mvn test
  - jdk_switcher use oraclejdk8
  - mvn test